name: Build and Deploy Lambda

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. GitHub Repository 가져오기
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. Amazon Linux 2023 환경에서 C++ 컴파일
      - name: Build C++ Lambda
        run: |
          docker run --rm \
            -v "$PWD:/workspace" \
            -w /workspace \
            public.ecr.aws/lambda/provided:al2023 \
            bash -c '
              dnf install -y gcc-c++ zip

              echo "===== C++ Compiler ====="
              g++ --version

              echo "===== Build ====="

              g++ -std=c++17 \
                *.cpp \
                -o bootstrap

              chmod +x bootstrap

              echo "===== Bootstrap ====="
              ls -lh bootstrap
              file bootstrap
            '

      # 3. Lambda deployment package 생성
      - name: Create Lambda package
        run: |
          rm -f lambda.zip

          zip lambda.zip bootstrap

          echo "===== Lambda Package ====="
          ls -lh lambda.zip
          unzip -l lambda.zip

      # 4. AWS OIDC 인증
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::436395637726:role/Photo_Share_Role
          aws-region: ap-northeast-2

      # 5. AWS 인증 확인
      - name: Check AWS Identity
        run: |
          aws sts get-caller-identity

      # 6. Lambda에 새 코드 배포
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name Photo_share_main \
            --zip-file fileb://lambda.zip

      # 7. 배포 완료 확인
      - name: Check Lambda
        run: |
          aws lambda get-function-configuration \
            --function-name Photo_share_main \
            --query '{
              FunctionName:FunctionName,
              Runtime:Runtime,
              Architecture:Architectures[0],
              LastModified:LastModified
            }'

